"""Add skills and benefits tables

Revision ID: 1d1296900a68
Revises: 1cd9f62eaa79
Create Date: 2025-03-15 07:00:57.886760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1296900a68'
down_revision: Union[str, None] = '1cd9f62eaa79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 