"""add interviews table

Revision ID: b4410c0e9187
Revises: 381b5658cd7f
Create Date: 2025-03-14 23:06:52.597723

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4410c0e9187"
down_revision: Union[str, None] = "381b5658cd7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("application_id", sa.String(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "interview_type",
            sa.Enum(
                "PHONE",
                "VIDEO",
                "IN_PERSON",
                "TECHNICAL",
                "BEHAVIORAL",
                "FINAL",
                name="interviewtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "COMPLETED", "CANCELLED", "NO_SHOW", name="interviewstatus"
            ),
            nullable=False,
        ),
        sa.Column("meeting_link", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["job_applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interviews")
    # ### end Alembic commands ###
